name: Pruebas Automatizadas

on:
  push:
    branches:
      - main

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Chrome
        steps:
          - uses: browser-actions/setup-chrome@v1
          - run: chrome --version
          
      - name: Run Tests
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/regression.xml
