name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Install Maven
        run: sudo apt-get install -y maven
          
      - name: Run Tests
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/regression.xml
